# Generated by Django 3.1.3 on 2021-01-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1_variant_id', models.IntegerField()),
                ('subject_2_variant_id', models.IntegerField()),
                ('subject_3_variant_id', models.IntegerField()),
                ('subject_4_variant_id', models.IntegerField()),
                ('subject_5_variant_id', models.IntegerField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_variant_number', models.IntegerField()),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exam_img')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exam_img')),
                ('is_correct', models.BooleanField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSubjectsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_subject_id', models.IntegerField()),
                ('second_subject_id', models.IntegerField()),
                ('subj1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subj1', to='exam.examsubject')),
                ('subj2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examsubject')),
            ],
        ),
    ]
