# Generated by Django 3.1.3 on 2021-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
