# Generated by Django 3.1.3 on 2021-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Name', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Surname', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='nomail@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345678', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+700000000', max_length=16),
        ),
    ]
