# Generated by Django 3.1.3 on 2021-01-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20210110_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название категории', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.CharField(default='no_ip', max_length=256),
        ),
        migrations.CreateModel(
            name='CategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.category')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.variant')),
            ],
        ),
    ]
