# Generated by Django 3.1.3 on 2021-01-11 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 1, 11)),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(default='+700000000', max_length=16),
        ),
    ]
