# Generated by Django 3.1.3 on 2021-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20210111_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='no token', max_length=256)),
                ('email', models.EmailField(default='nomail@mail.com', max_length=254)),
            ],
        ),
    ]
